default:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/tmp/duck-db/nfl_pbp.duckdb'
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: "{{ env_var('AWS_DEFAULT_REGION') }}"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"